In [2]:
# Import Library

import numpy as np

NumPy is short for "Numerical Python". NumPy is used for working with arrays and matrices.

## Creating Numpy Array from List

In [3]:
#Python List
L = [1, 2, 3, 4, 5]
print("\nList :",L)

#Numpy Array
A = np.array([1, 2, 3, 4, 5])
print("\nArray :",A)


List : [1, 2, 3, 4, 5]

Array : [1 2 3 4 5]


In [4]:
#Multi-dimensional Arrays

AA = np.array([[1, 2, 3], [4, 5, 6]])
print("\nPrinting 2D array:\n", AA)

AAA = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\nPrinting 3D array:\n",AAA)


Printing 2D array:
 [[1 2 3]
 [4 5 6]]

Printing 3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [74]:
# check array dimensions

print("\nDimensions of AA:", AA.ndim)
print("\nDimensions of AAA:", AAA.ndim)


Dimensions of AA: 2

Dimensions of AAA: 3


# Indexing 

The indexes in NumPy arrays start with 0.
The first element has index 0.

In [43]:
#Indexing

A = np.array([1, 2, 3, 4])
print("\nFirst element of A:", A[0]) 

AA = np.array([[1, 2, 3], [4, 5, 6]])

print("\nElement in the first row & second column of AA:", AA[0][1]) 
print("\nElement in the second row & first column of AA:",AA[1][0]) 

AAA = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\nThird element of the second array of the first array in AAA:",AAA[0][1][2]) 


First element of A: 1

Element in the first row & second column of AA: 2

Element in the second row & first column of AA: 4

Third element of the second array of the first array in AAA: 6


# Slicing

Slicing in taking elements from one given index to another given index: [start:end]

The result includes the start index, but excludes the end index.

If we don't pass start index, its considered 0.

If we don't pass the end index, its considered length of array in that dimension.

In [36]:
#Slicing

A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print("\nSlice from first element/ index 0 to fifth element/ index 4:", A[0:5])

print("\nSlice from second element/ index 1 to fifth element/ index 4:", A[1:5])

print("\nSlice from index 4 to the end:", A[4:])

print("\nSlice from start to index 3:", A[:4])


Slice from first element/ index 0 to fifth element/ index 4: [1 2 3 4 5]

Slice from second element/ index 1 to fifth element/ index 4: [2 3 4 5]

Slice from index 4 to the end: [5 6 7 8]

Slice from start to index 3: [1 2 3 4]


In [50]:
#Slicing- 2D Array

AA = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(AA)

print("\nSelect second row, slice from index 1 to index 3: \n", AA[1, 1:4])

print("\nSlice third column: \n", AA[:, 2])

print("\nSelect rows 1 and 2, Slice third column: \n", AA[0:2, 2])

print("\nSelect rows 1 and 2, slice columns 2 to 4: \n", AA[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Select second row, slice from index 1 to index 3: 
 [7 8 9]

Slice third column: 
 [3 8]

Select rows 1 and 2, Slice third column: 
 [3 8]

Select rows 1 and 2, slice columns 2 to 4: 
 [[2 3 4]
 [7 8 9]]


# Array Shapes
The shape of an array is the number of elements in each dimension.

In [64]:
#shape

AA = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(AA)

print('\nshape of array :', AA.shape)

[[1 2 3 4]
 [5 6 7 8]]

shape of array : (2, 4)


## Reshaping Arrays
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [65]:
#Reshape

A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print('\nshape of array A:', A.shape)

new_A = A.reshape(4, 3)

print('\nReshaped Array:\n', new_A)
print('\nshape of array new_A:', new_A.shape)


shape of array A: (12,)

Reshaped Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

shape of array new_A: (4, 3)


In [88]:
A = np.array([1, 2, 3, 4, 5])
print("This is a 1D array with 5 elements.",A)
print("\nDimensions of A:", A.ndim)

A1 = A.reshape(5,1)
print("\nreshape(5,1): we get a 2D array with 5 rows and 1 column\n",A1)
print("\nThough there is a single column, the array dimension is 2-D")
print("\nDimensions of A1:", A1.ndim)

A2 = A.reshape(1,5)
print("\nreshape(1,5): we get a 2D array with 1 row and 5 columns\n",A2)
print("\nThough there is a single row, the array dimension is 2-D")
print("\nDimensions of A2:", A2.ndim)



This is a 1D array with 5 elements. [1 2 3 4 5]

Dimensions of A: 1

reshape(5,1): we get a 2D array with 5 rows and 1 column
 [[1]
 [2]
 [3]
 [4]
 [5]]

Though there is a single column, the array dimension is 2-D

Dimensions of A1: 2

reshape(1,5): we get a 2D array with 1 row and 5 columns
 [[1 2 3 4 5]]

Though there is a single row, the array dimension is 2-D

Dimensions of A2: 2


In [89]:
#Reshape(-1,1)

A3 = A.reshape(-1,1)
print("\nreshape(-1,1):We can specify column as 1, leaving rows number open, denoted by -1\n", A3)


A4 = A.reshape(1,-1)
print("\nreshape(1,-1):We can specify row as 1, leaving column number open, denoted by -1\n",A4)


reshape(-1,1):We can specify column as 1, leaving rows number open, denoted by -1
 [[1]
 [2]
 [3]
 [4]
 [5]]

reshape(1,-1):We can specify row as 1, leaving column number open, denoted by -1
 [[1 2 3 4 5]]
